export const products = [
  {
    id: 1,
    name: "Noodles With Tomato",
    image: require("../assets/images/foods/makanan1.png"),
    category: "makanan",
    price: 13000,
  },
  {
    id: 2,
    name: "Roasted Pork Belly",
    image: require("../assets/images/foods/makanan2.png"),
    category: "makanan",
    price: 14000,
  },
  {
    id: 3,
    name: "Eggplant Connellino",
    image: require("../assets/images/foods/makanan3.png"),
    category: "makanan",
    price: 12000,
  },
  {
    id: 4,
    name: "Chocolate Cake",
    image: require("../assets/images/foods/makanan4.png"),
    category: "makanan",
    price: 15000,
  },
  {
    id: 5,
    name: "Strawberry Pavlova Cake",
    image: require("../assets/images/foods/makanan5.png"),
    category: "makanan",
    price: 12000,
  },
  {
    id: 6,
    name: "Pizza Salami",
    image: require("../assets/images/foods/makanan6.png"),
    category: "makanan",
    price: 17000,
  },
  {
    id: 7,
    name: "Roasted Pork Ribs",
    image: require("../assets/images/foods/makanan7.png"),
    category: "makanan",
    price: 12000,
  },
  {
    id: 8,
    name: "Spageti With Tomato",
    image: require("../assets/images/foods/makanan8.jpg"),
    category: "makanan",
    price: 19000,
  },
  {
    id: 9,
    name: "Healty Green Salad",
    image: require("../assets/images/foods/makanan9.png"),
    category: "makanan",
    price: 12000,
  },
  {
    id: 10,
    name: "Fried Rice",
    image: require("../assets/images/foods/makanan10.png"),
    category: "makanan",
    price: 12000,
  },
  {
    id: 11,
    name: "Noodles With Tomato",
    image: require("../assets/images/foods/makanan1.png"),
    category: "makanan",
    price: 13000,
  },
  {
    id: 12,
    name: "Roasted Pork Belly",
    image: require("../assets/images/foods/makanan2.png"),
    category: "makanan",
    price: 14000,
  },
  {
    id: 13,
    name: "Eggplant Connellino",
    image: require("../assets/images/foods/makanan3.png"),
    category: "makanan",
    price: 12000,
  },
  {
    id: 14,
    name: "Chocolate Cake",
    image: require("../assets/images/foods/makanan4.png"),
    category: "makanan",
    price: 15000,
  },
  {
    id: 15,
    name: "Strawberry Pavlova Cake",
    image: require("../assets/images/foods/makanan5.png"),
    category: "makanan",
    price: 12000,
  },
];
